//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtractDBLPForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class author
    {
        public int id { get; set; }
        public string mdate { get; set; }
        public string key { get; set; }
        public string name { get; set; }
        public string crossref { get; set; }
        public string alias { get; set; }
        public string url { get; set; }
        public string articles_keys { get; set; }
        public string inproceedings_keys { get; set; }
        public string title { get; set; }
        public Nullable<int> count { get; set; }
    }
}
