//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtractDBLPForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class dblp_inproceedings
    {
        public int id { get; set; }
        public string key { get; set; }
        public string title { get; set; }
        public string authors { get; set; }
        public string conference { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> conference_id { get; set; }
        public string year { get; set; }
        public string ee { get; set; }
        public string url { get; set; }
        public string pages { get; set; }
        public string crossref { get; set; }
        public string mdate { get; set; }
    }
}
