//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtractDBLPForm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dblpData : DbContext
    {
        public dblpData()
            : base("name=dblpData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<article> articles { get; set; }
        public DbSet<author> authors { get; set; }
        public DbSet<dblp_author> dblp_author { get; set; }
        public DbSet<dblp_conference> dblp_conference { get; set; }
        public DbSet<dblp_inproceedings> dblp_inproceedings { get; set; }
        public DbSet<inproceeding> inproceedings { get; set; }
        public DbSet<phdthesi> phdthesis { get; set; }
        public DbSet<proceedings> proceedings { get; set; }
        public DbSet<table_articles> table_articles { get; set; }
        public DbSet<table_inproceedings> table_inproceedings { get; set; }
        public DbSet<table_phdthesis> table_phdthesis { get; set; }
        public DbSet<table_proceedings> table_proceedings { get; set; }
        public DbSet<table_www> table_www { get; set; }
    }
}
