//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtractDBLPForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class phdthesi
    {
        public int id { get; set; }
        public string title { get; set; }
        public string authors { get; set; }
        public string key { get; set; }
        public string mdate { get; set; }
        public string year { get; set; }
        public string school { get; set; }
        public string pages { get; set; }
        public string isbn { get; set; }
        public string note { get; set; }
    }
}
