//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtractDBLPForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_phdthesis
    {
        public int ID { get; set; }
        public string KEY { get; set; }
        public string MDATE { get; set; }
        public string TITLE { get; set; }
        public string PAGES { get; set; }
        public Nullable<int> YEAR { get; set; }
        public string SCHOOL { get; set; }
        public string NOTE { get; set; }
        public string URL { get; set; }
        public string CROSSREF { get; set; }
        public string AUTHORS { get; set; }
        public Nullable<int> COUNT { get; set; }
        public string author_keys { get; set; }
    }
}
